#!/bin/sh
mount -t drvfs x: /mnt/x
mkdir -p /mnt/x/CORSAIR/D
rsync -r --size-only --delete --stats /mnt/d/ /mnt/x/CORSAIR/D --exclude='$RECYCLE.BIN' --exclude="System Volume Information" --exclude 'node_modules'
